[2025-10-02T01:45:04.848+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-02T01:45:04.868+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: alpha_vantage_to_snowflake.execute_pipeline scheduled__2025-10-02T01:30:00+00:00 [queued]>
[2025-10-02T01:45:04.878+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: alpha_vantage_to_snowflake.execute_pipeline scheduled__2025-10-02T01:30:00+00:00 [queued]>
[2025-10-02T01:45:04.879+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-10-02T01:45:04.891+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): execute_pipeline> on 2025-10-02 01:30:00+00:00
[2025-10-02T01:45:04.903+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1593) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-02T01:45:04.900+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'alpha_vantage_to_snowflake', 'execute_pipeline', 'scheduled__2025-10-02T01:30:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/alpha_vantage_to_snowflake.py', '--cfg-path', '/tmp/tmpnmsvoenl']
[2025-10-02T01:45:04.904+0000] {standard_task_runner.py:72} INFO - Started process 1596 to run task
[2025-10-02T01:45:04.904+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask execute_pipeline
[2025-10-02T01:45:04.952+0000] {task_command.py:467} INFO - Running <TaskInstance: alpha_vantage_to_snowflake.execute_pipeline scheduled__2025-10-02T01:30:00+00:00 [running]> on host dc0cf9892ce9
[2025-10-02T01:45:05.058+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='alpha_vantage_to_snowflake' AIRFLOW_CTX_TASK_ID='execute_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T01:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-02T01:30:00+00:00'
[2025-10-02T01:45:05.061+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-02T01:45:05.077+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-02T01:45:05.078+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-10-02T01:45:05.080+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-02T01:45:05.080+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-02T01:45:06.038+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-02T01:45:06.149+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-02T01:45:16.322+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
