[2025-10-04T19:00:04.009+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-04T19:00:04.039+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: alpha_vantage_to_snowflake.execute_pipeline scheduled__2025-10-04T18:45:00+00:00 [queued]>
[2025-10-04T19:00:04.053+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: alpha_vantage_to_snowflake.execute_pipeline scheduled__2025-10-04T18:45:00+00:00 [queued]>
[2025-10-04T19:00:04.056+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-10-04T19:00:04.073+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): execute_pipeline> on 2025-10-04 18:45:00+00:00
[2025-10-04T19:00:04.090+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=926) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-04T19:00:04.093+0000] {standard_task_runner.py:72} INFO - Started process 929 to run task
[2025-10-04T19:00:04.090+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'alpha_vantage_to_snowflake', 'execute_pipeline', 'scheduled__2025-10-04T18:45:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/alpha_vantage_to_snowflake.py', '--cfg-path', '/tmp/tmp2rr0vyxk']
[2025-10-04T19:00:04.096+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask execute_pipeline
[2025-10-04T19:00:04.189+0000] {task_command.py:467} INFO - Running <TaskInstance: alpha_vantage_to_snowflake.execute_pipeline scheduled__2025-10-04T18:45:00+00:00 [running]> on host a2bdf5c201a5
[2025-10-04T19:00:04.368+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='alpha_vantage_to_snowflake' AIRFLOW_CTX_TASK_ID='execute_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-10-04T18:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-04T18:45:00+00:00'
[2025-10-04T19:00:04.373+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-04T19:00:04.397+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T19:00:04.399+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-10-04T19:00:04.403+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T19:00:04.404+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T19:00:06.232+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-04T19:00:06.395+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-04T19:01:36.172+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-04T19:01:36.174+0000] {logging_mixin.py:190} INFO - Data inserted successfully into Snowflake table
[2025-10-04T19:01:36.176+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-04T19:01:36.195+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-04T19:01:36.196+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=alpha_vantage_to_snowflake, task_id=execute_pipeline, run_id=scheduled__2025-10-04T18:45:00+00:00, execution_date=20251004T184500, start_date=20251004T190004, end_date=20251004T190136
[2025-10-04T19:01:36.250+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-04T19:01:36.278+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-04T19:01:36.282+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
